// Auto-generated by test_cov. Do not edit by hand.

import 'cache_version_test.dart' as cache_version_test;
import 'commands_test.dart' as commands_test;
import 'flutter_app_service_test.dart' as flutter_app_service_test;
import 'releases_api_test.dart' as releases_api_test;
import 'services/cache_service_test.dart' as services_cache_service_test;
import 'utils/helpers_test.dart' as utils_helpers_test;
import 'utils/releases_test.dart' as utils_releases_test;

void main() {
  cache_version_test.main();
  releases_api_test.main();
  services_cache_service_test.main();
  flutter_app_service_test.main();
  commands_test.main();
  utils_helpers_test.main();
  utils_releases_test.main();
}
