include: package:lints/recommended.yaml
analyzer:
# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/recommended.yaml
    - package:dart_code_metrics_presets/metrics_recommended.yaml
  metrics-exclude:
    - test/**
  rules-exclude:
    - test/**
  rules:
    newline-before-return: true
    avoid-importing-entrypoint-exports:
        only-in-src: true
    prefer-match-file-name: false
    prefer-correct-callback-field-name: false
    match-getter-setter-field-names: false
    avoid-duplicate-cascades: false
    prefer-dedicated-media-query-methods: false
    avoid-shadowing: false
    avoid-duplicate-initializers: false
    enum-constants-ordering: false
    avoid-accessing-collections-by-constant-index: false
    avoid-unsafe-collection-methods: false
    move-variable-closer-to-its-usage: false
    prefer-prefixed-global-constants: false
    avoid-nullable-interpolation: false
    avoid-returning-widgets: false
    avoid-nested-conditional-expressions:
        acceptable-level: 3
    member-ordering:
        order:
          - public-fields
          - private-fields
          - constructors
          - static-methods
          - private-methods
          - private-getters
          - private-setters
          - public-getters
          - public-setters
          - public-methods
          - overridden-public-methods
          - overridden-public-getters
          - build-method
    prefer-named-boolean-parameters:
      ignore-single: true