name: "Prepare"
description: "Prepare and tests the project"

inputs:
  sdk-version:
    description: "Dart SDK version"
    required: false
    # 3.4.1 Version tested and within the compatibility
    default: "3.4.1"

runs:
  using: "composite"
  steps:
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ inputs.sdk-version }} 

    - name: Get dependencies
      run: dart pub get
      shell: bash
